// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2eNJyCMRRM-SZ-BtShjWQPFk8Xbb_7OE',
    appId: '1:468065221022:web:47420f335756bd2a823e8f',
    messagingSenderId: '468065221022',
    projectId: 'propairx',
    authDomain: 'propairx.firebaseapp.com',
    storageBucket: 'propairx.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3oZZO2PJtmpxQT1rptEkihxJBTuaKlTs',
    appId: '1:468065221022:android:a6fbc50bcc656b1d823e8f',
    messagingSenderId: '468065221022',
    projectId: 'propairx',
    storageBucket: 'propairx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYvXkNWk_unTRLpqLBg3TqI_2nQp-ZQfY',
    appId: '1:468065221022:ios:ae48e4be0b6f5fa2823e8f',
    messagingSenderId: '468065221022',
    projectId: 'propairx',
    storageBucket: 'propairx.firebasestorage.app',
    iosBundleId: 'com.example.propairx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYvXkNWk_unTRLpqLBg3TqI_2nQp-ZQfY',
    appId: '1:468065221022:ios:ae48e4be0b6f5fa2823e8f',
    messagingSenderId: '468065221022',
    projectId: 'propairx',
    storageBucket: 'propairx.firebasestorage.app',
    iosBundleId: 'com.example.propairx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2eNJyCMRRM-SZ-BtShjWQPFk8Xbb_7OE',
    appId: '1:468065221022:web:a8aeb2f6e455e21a823e8f',
    messagingSenderId: '468065221022',
    projectId: 'propairx',
    authDomain: 'propairx.firebaseapp.com',
    storageBucket: 'propairx.firebasestorage.app',
  );
}
